# This YAML file describes your package. Stack will automatically generate a
# Cabal file when you run `stack build`. See the hpack website for help with
# this file: <https://github.com/sol/hpack>.
name: morottaja
version: '0.0.0'
# github: "githubuser/morottaja"
license: MIT
author: "Author name here"
maintainer: "Author name here"
# synopsis: A new Haskeleton package.
description: Lataa annetun p채iv채n Aamulehden ja muuntaa PDF:ksi Imagemagickia apuna k채ytt채en.
# category: Other

extra-source-files:
- CHANGELOG.md
- LICENSE.md
- package.yaml
- README.md
- stack.yaml

ghc-options: -Wall

library:
  dependencies:
  - base
  - aeson
  - bytestring
  - http-conduit
  - text
  - time
  source-dirs: library

executables:
  morottaja:
    source-dirs: executable
    main: Main.hs
    dependencies:
    - base
    - morottaja
    ghc-options:
    - -rtsopts
    - -threaded
    - -with-rtsopts=-N

benchmarks:
  morottaja-benchmarks:
    source-dirs: benchmark
    main: Main.hs
    dependencies:
    - base
    - morottaja
    - criterion
    ghc-options:
    - -rtsopts
    - -threaded
    - -with-rtsopts=-N

tests:
  morottaja-test-suite:
    source-dirs: test-suite
    main: Main.hs
    dependencies:
    - base
    - morottaja
    - tasty
    - tasty-hspec
    ghc-options:
    - -rtsopts
    - -threaded
    - -with-rtsopts=-N
